#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

TFileHandle fileHandler;
TFileIOResult nIOResult;
string fileName = "data.txt";
int nFileSize = 20000;
string data;
byte CR = 13;
byte LF = 10;

int kran_angle = 90;
float kran_length = 10.0;
float kran_x = 0.0;
float kran_y = kran_length;
float picture_length = 10.0;
float wheel_radius = 5.6;
float wheel_length = 2 * wheel_radius * PI;
int dark = 50;

void write (float x, float y)
{
		data = "";
		StringFormat(data, "%f %f", x, y);
		WriteString(fileHandler, nIOResult, data);
		WriteByte(fileHandler, nIOResult, CR);
		WriteByte(fileHandler, nIOResult, LF);
}

void moveKran ()
{
		--kran_angle;
		nMotorEncoder[motorA] = 0;
		motor[motorA] = 1;
		while (nMotorEncoder[motorA] == 0){};
		motor[motorA] = 0;
		kran_x = kran_length * cosDegrees (kran_angle);
		kran_y = kran_length * sinDegrees (kran_angle);
}

void moveRobot (bool direction)
{
		nMotorEncoder[motorB] = 0;
		int cnt, z;
		float distance = 0.0, x, y;
		while (nMotorEncoder[motorB] / 360.0 * wheel_length < picture_length)
		{
				cnt = nMotorEncoder[motorB];
				motor[motorB] = motor[motorC] = (direction ? 1 : -1);
				while (nMotorEncoder[motorB] == cnt) {};
				motor[motorB] = motor[motorC] = 0;
				distance += 1.0 / 360.0 * wheel_length;
				x = kran_x;
				y = distance + (direction ? 1.0 : -1.0) * (kran_y - kran_length);
				z = SensorValue (lightSensor);
				if (z <= dark) write (x, y);
		}
}

task main()
{
		Delete(fileName,nIOResult);
		OpenWrite(fileHandler, nIOResult, fileName, nFileSize);
		
		for (int i = 0; i <= 90; ++i)
		{		
				moveRobot ((i % 2 == 0));
				moveKran ();
		}
		
		Close(fileHandler, nIOResult);
}